Update go version, bump direct deps to latest minor/patch, address supply chain security alert, remove unused pipeline yml, configure dependabot (#158)
* Remove unused Azure Pipelines YAML

* Inline Go version lookup in schema pipeline

* Bump Go and go-git versions

* Updated pool to ubuntu 2404

* Add Dependabot configuration

* Updated Dockerfile base image to comply with supply chain security scanner

* Bump direct go deps to latest minor/patch

diff --git a/.azdo/azurerm-schema-update-pipeline.yml b/.azdo/azurerm-schema-update-pipeline.yml
--- a/.azdo/azurerm-schema-update-pipeline.yml
+++ b/.azdo/azurerm-schema-update-pipeline.yml
@@ -10,11 +10,10 @@ parameters:
     default: main
 
 pool:
-  name: pool-ubuntu-2004
+  name: pool-ubuntu-2404
 
 variables:
   GOBIN:  '$(GOPATH)/bin' # Go binaries path
-  GOROOT: '/usr/local/go1.11' # Go installation path
   GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
   modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code
   moduleDir: '$(GOPATH)/src/github.com'
@@ -28,12 +27,19 @@ steps:
     name: step1
 
   - script: |
-      wget https://go.dev/dl/go1.23.3.linux-amd64.tar.gz
-      sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.23.3.linux-amd64.tar.gz
-      export GOROOT=/usr/local/go
-      export PATH=$GOROOT/bin:$PATH
-      go version
-    displayName: 'Set up the Go workspace'
+      set -euo pipefail
+      go_version="$(awk '/^go [0-9]+\.[0-9]+(\.[0-9]+)?$/ { print $2; exit }' go.mod)"
+      if [[ -z "${go_version}" ]]; then
+        echo "failed to read go version from go.mod" >&2
+        exit 1
+      fi
+      echo "##vso[task.setvariable variable=GO_VERSION]${go_version}"
+    displayName: 'Read Go version from go.mod'
+
+  - task: GoTool@0
+    displayName: 'Install Go from go.mod'
+    inputs:
+      version: $(GO_VERSION)
 
   - script: |
       git config --global user.email "henglu@microsoft.com"
@@ -53,8 +59,6 @@ steps:
       PAT: $(PAT)
 
   - bash: |
-      export GOROOT=/usr/local/go
-      export PATH=$GOROOT/bin:$PATH
       cd aztfmigrate/.tools/generate-provider-schema
       pwd
       chmod -R +x ./run.sh
@@ -62,8 +66,6 @@ steps:
     displayName: 'Exporting AzureRM Schema'
 
   - bash: |
-      export GOROOT=/usr/local/go
-      export PATH=$GOROOT/bin:$PATH
       export TAG=$(step1.TAG)
       cd aztfmigrate
       make fmt
